### ISSUE TITLE
[BUG] GUI not lauched. AttributeError: 'QCheckBox' has no attribute 'checkStateChanged' in `gui.py`

### ISSUE THREAD

**Issue by elemeng** [MouseLand/cellpose#1215]
**Title:** AttributeError: 'QCheckBox' has no attribute 'checkStateChanged' in `gui.py`

Hi Cellpose team,

Thanks for the excellent work on Cellpose — it's a very helpful tool for my image analysis work.

While launching the GUI using the latest version installed via conda/pip, I encountered the following error:

```
Traceback (most recent call last):
  File "C:\Users\Tom\miniforge3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Tom\miniforge3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Tom\miniforge3\Scripts\cellpose.exe\__main__.py", line 7, in <module>
  File "C:\Users\Tom\miniforge3\lib\site-packages\cellpose\__main__.py", line 54, in main
    gui.run()
  File "C:\Users\Tom\miniforge3\lib\site-packages\cellpose\gui\gui.py", line 169, in run
    MainW(image=image, logger=logger)
  File "C:\Users\Tom\miniforge3\lib\site-packages\cellpose\gui\gui.py", line 277, in __init__
    self.autobtn.checkStateChanged.connect(self.compute_saturation_if_checked)
AttributeError: 'QCheckBox' object has no attribute 'checkStateChanged'
```

It seems that `checkStateChanged` is not a valid signal for `QCheckBox`. According to the PyQt/PySide documentation, the correct signal is:

```python
stateChanged
```

So the line in `gui.py` should probably be:

```python
self.autobtn.stateChanged.connect(self.compute_saturation_if_checked)
```

Making this change locally resolved the issue for me.

Let me know if I can help with a pull request.

Best regards,
Ele

**Comment by christianrickert** [comment]
Just ran into the same issue. Quick workaround is to uninstall PyQT5 - if PyQT6 is already in the environment and there's no other module requiring the older version:

```Python
python -m pip uninstall PytQt5  # no need to set up a new venv
```

PyQT5 was introduced with PR #849 and then this requirement was relaxed (effectively to PyQT6) with the latest commit 26ee44e86bf4d3c824a20d3973ec3188bf97bea8 as far as I can tell.

I've made a simple change to the gui code that checks for the installed PyQT version and changes the function call accordingly. Please let me know if you would like me to make a PR.

**Comment by nosferachos** [comment]
Hi all! New to Cellpose and coding in general here, trying to run Cellpose 4 on a MacBook Air M2 from 2023,
encountered the same issue when trying to launch the GUI.. 

To sum up, I started by using this command:
`python -m pip install 'cellpose[gui]`

This successfully installed the environment, so I tired running it by using
`python -m cellpose`

Here I get this error:  " AttributeError: 'QCheckBox' object has no attribute 'checkStateChanged' "

So based on this discussion I went ahead and checked the pip list, here is what I first got:

Package                           Version
--------------------------------- ------------------
aext-assistant                    4.20.0
aext-assistant-server             4.20.0
aext-core                         4.20.0
aext-core-server                  4.20.0
aext_environments_server          4.20.0
aext-panels                       4.20.0
aext-panels-server                4.20.0
aext-project-filebrowser-server   4.20.0
aext-share-notebook               4.20.0
aext-share-notebook-server        4.20.0
aext-shared                       4.20.0
aext-toolbox                      4.20.0
aiobotocore                       2.12.3
aiohappyeyeballs                  2.4.0
aiohttp                           3.10.5
aioitertools                      0.7.1
aiosignal                         1.2.0
alabaster                         0.7.16
alembic                           1.13.3
altair                            5.0.1
anaconda-anon-usage               0.4.4
anaconda-auth                     0.8.6
anaconda-catalogs                 0.2.0
anaconda-cli-base                 0.5.2
anaconda-client                   1.13.0
anaconda-navigator                2.6.6
anaconda-project                  0.11.1
annotated-types                   0.6.0
anyio                             4.2.0
appdirs                           1.4.4
applaunchservices                 0.3.0
appnope                           0.1.3
appscript                         1.2.5
archspec                          0.2.3
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
arrow                             1.2.3
astroid                           2.14.2
astropy                           6.1.3
astropy-iers-data                 0.2024.9.2.0.33.23
asttokens                         2.0.5
async-lru                         2.0.4
atomicwrites                      1.4.0
attrs                             23.1.0
Automat                           20.2.0
autopep8                          2.0.4
Babel                             2.11.0
bcrypt                            3.2.0
beautifulsoup4                    4.12.3
binaryornot                       0.4.4
black                             24.8.0
bleach                            4.1.0
blinker                           1.6.2
bokeh                             3.6.0
boltons                           23.0.0
botocore                          1.34.69
Bottleneck                        1.3.7
Brotli                            1.0.9
cachetools                        5.3.3
cellpose                          4.0.4
certifi                           2025.4.26
cffi                              1.17.1
chardet                           4.0.0
charset-normalizer                3.3.2
click                             8.1.7
cloudpickle                       3.0.0
colorama                          0.4.6
colorcet                          3.1.0
comm                              0.2.1
conda                             24.11.3
conda-build                       24.9.0
conda-content-trust               0.2.0
conda_index                       0.5.0
conda-libmamba-solver             24.9.0
conda-pack                        0.7.1
conda-package-handling            2.3.0
conda_package_streaming           0.10.0
conda-repo-cli                    1.0.114
conda-token                       0.6.0
constantly                        23.10.4
contourpy                         1.2.0
cookiecutter                      2.6.0
cryptography                      43.0.0
cssselect                         1.2.0
cycler                            0.11.0
cytoolz                           0.12.2
dask                              2024.8.2
dask-expr                         1.1.13
datashader                        0.16.3
debugpy                           1.6.7
decorator                         5.1.1
defusedxml                        0.7.1
diff-match-patch                  20200713
dill                              0.3.8
distributed                       2024.8.2
distro                            1.9.0
dmglib                            0.9.5
docstring-to-markdown             0.11
docutils                          0.18.1
et-xmlfile                        1.1.0
executing                         0.8.3
fastjsonschema                    2.16.2
fastremap                         1.16.1
filelock                          3.13.1
fill_voids                        2.1.0
flake8                            7.0.0
Flask                             3.0.3
fonttools                         4.51.0
frozendict                        2.4.2
frozenlist                        1.4.0
fsspec                            2024.6.1
gensim                            4.3.3
gitdb                             4.0.7
GitPython                         3.1.43
greenlet                          3.0.1
h11                               0.14.0
h5py                              3.11.0
HeapDict                          1.0.1
holoviews                         1.19.1
httpcore                          1.0.2
httpx                             0.27.0
hvplot                            0.11.0
hyperlink                         21.0.0
idna                              3.7
imagecodecs                       2023.1.23
imageio                           2.33.1
imagesize                         1.4.1
imbalanced-learn                  0.12.3
importlib-metadata                7.0.1
incremental                       22.10.0
inflection                        0.5.1
iniconfig                         1.1.1
intake                            2.0.7
intervaltree                      3.1.0
ipykernel                         6.28.0
ipython                           8.27.0
ipython-genutils                  0.2.0
ipywidgets                        7.8.1
isort                             5.13.2
itemadapter                       0.3.0
itemloaders                       1.1.0
itsdangerous                      2.2.0
jaraco.classes                    3.2.1
jedi                              0.19.1
jellyfish                         1.0.1
Jinja2                            3.1.4
jmespath                          1.0.1
joblib                            1.4.2
json5                             0.9.6
jsonpatch                         1.33
jsonpointer                       2.1
jsonschema                        4.23.0
jsonschema-specifications         2023.7.1
jupyter                           1.0.0
jupyter_client                    8.6.0
jupyter-console                   6.6.3
jupyter_core                      5.7.2
jupyter-events                    0.10.0
jupyter-lsp                       2.2.0
jupyter_server                    2.14.1
jupyter_server_terminals          0.4.4
jupyterlab                        4.2.5
jupyterlab-pygments               0.1.2
jupyterlab_server                 2.27.3
jupyterlab-widgets                1.0.0
keyring                           24.3.1
kiwisolver                        1.4.4
lazy_loader                       0.4
lazy-object-proxy                 1.10.0
lckr_jupyterlab_variableinspector 3.1.0
libarchive-c                      5.1
libmambapy                        1.5.8
linkify-it-py                     2.0.0
llvmlite                          0.43.0
lmdb                              1.4.1
locket                            1.0.0
lxml                              5.2.1
lz4                               4.3.2
Mako                              1.2.3
Markdown                          3.4.1
markdown-it-py                    2.2.0
MarkupSafe                        2.1.3
matplotlib                        3.9.2
matplotlib-inline                 0.1.6
mccabe                            0.7.0
mdit-py-plugins                   0.3.0
mdurl                             0.1.0
menuinst                          2.1.2
mistune                           2.0.4
more-itertools                    10.3.0
mpmath                            1.3.0
msgpack                           1.0.3
multidict                         6.0.4
multipledispatch                  0.6.0
mypy                              1.11.2
mypy-extensions                   1.0.0
natsort                           8.4.0
navigator-updater                 0.5.1
nb_conda_kernels                  2.5.2
nbclient                          0.8.0
nbconvert                         7.16.4
nbformat                          5.10.4
nest-asyncio                      1.6.0
networkx                          3.3
nltk                              3.9.1
notebook                          7.2.2
notebook_shim                     0.2.3
numba                             0.60.0
numexpr                           2.8.7
numpy                             1.26.4
numpydoc                          1.7.0
opencv-python-headless            4.11.0.86
openpyxl                          3.1.5
overrides                         7.4.0
packaging                         24.1
pandas                            2.2.2
pandocfilters                     1.5.0
panel                             1.5.2
param                             2.1.1
parsel                            1.8.1
parso                             0.8.3
partd                             1.4.1
pathspec                          0.10.3
patsy                             0.5.6
pexpect                           4.8.0
pickleshare                       0.7.5
pillow                            10.4.0
pip                               24.2
pkce                              1.0.3
pkginfo                           1.10.0
platformdirs                      3.10.0
plotly                            5.24.1
pluggy                            1.0.0
ply                               3.11
prometheus-client                 0.14.1
prompt-toolkit                    3.0.43
Protego                           0.1.16
protobuf                          4.25.3
psutil                            5.9.0
ptyprocess                        0.7.0
pure-eval                         0.2.2
py-cpuinfo                        9.0.0
pyarrow                           16.1.0
pyasn1                            0.4.8
pyasn1-modules                    0.2.8
pycodestyle                       2.11.1
pycosat                           0.6.6
pycparser                         2.21
pyct                              0.5.0
pycurl                            7.45.3
pydantic                          2.8.2
pydantic_core                     2.20.1
pydantic-settings                 2.6.1
pydeck                            0.8.0
PyDispatcher                      2.0.5
pydocstyle                        6.3.0
pyerfa                            2.0.1.4
pyflakes                          3.2.0
Pygments                          2.15.1
PyJWT                             2.8.0
pylint                            2.16.2
pylint-venv                       3.0.3
pyls-spyder                       0.4.0
pyobjc-core                       10.1
pyobjc-framework-Cocoa            10.1
pyobjc-framework-CoreServices     10.1
pyobjc-framework-FSEvents         10.1
pyodbc                            5.1.0
pyOpenSSL                         24.2.1
pyparsing                         3.1.2
PyQt5                             5.15.10
PyQt5-sip                         12.13.0
PyQt6                             6.9.1
PyQt6-Qt6                         6.9.1
PyQt6_sip                         13.10.2
pyqtgraph                         0.13.7
PyQtWebEngine                     5.15.6
PySocks                           1.7.1
pytest                            7.4.4
python-dateutil                   2.9.0.post0
python-dotenv                     0.21.0
python-json-logger                2.0.7
python-lsp-black                  2.0.0
python-lsp-jsonrpc                1.1.2
python-lsp-server                 1.10.0
python-slugify                    5.0.2
pytoolconfig                      1.2.6
pytz                              2024.1
pyviz_comms                       3.0.2
PyWavelets                        1.7.0
PyYAML                            6.0.1
pyzmq                             25.1.2
QDarkStyle                        3.2.3
qstylizer                         0.2.2
QtAwesome                         1.3.1
qtconsole                         5.5.1
QtPy                              2.4.1
queuelib                          1.6.2
readchar                          4.0.5
referencing                       0.30.2
regex                             2024.9.11
requests                          2.32.3
requests-file                     1.5.1
requests-toolbelt                 1.0.0
rfc3339-validator                 0.1.4
rfc3986-validator                 0.1.1
rich                              13.7.1
roifile                           2025.5.10
rope                              1.12.0
rpds-py                           0.10.6
Rtree                             1.0.1
ruamel.yaml                       0.18.6
ruamel.yaml.clib                  0.2.8
ruamel-yaml-conda                 0.17.21
s3fs                              2024.6.1
scikit-image                      0.24.0
scikit-learn                      1.5.1
scipy                             1.13.1
Scrapy                            2.11.1
seaborn                           0.13.2
segment-anything                  1.0
semver                            3.0.2
Send2Trash                        1.8.2
sentry-sdk                        2.18.0
service-identity                  18.1.0
setuptools                        75.1.0
shellingham                       1.5.0
sip                               6.7.12
six                               1.16.0
smart-open                        5.2.1
smmap                             4.0.0
sniffio                           1.3.0
snowballstemmer                   2.2.0
sortedcontainers                  2.4.0
soupsieve                         2.5
Sphinx                            7.3.7
sphinxcontrib-applehelp           1.0.2
sphinxcontrib-devhelp             1.0.2
sphinxcontrib-htmlhelp            2.0.0
sphinxcontrib-jsmath              1.0.1
sphinxcontrib-qthelp              1.0.3
sphinxcontrib-serializinghtml     1.1.10
spyder                            5.5.1
spyder-kernels                    2.5.0
SQLAlchemy                        2.0.34
stack-data                        0.2.0
statsmodels                       0.14.2
streamlit                         1.37.1
superqt                           0.7.5
sympy                             1.14.0
tables                            3.10.1
tabulate                          0.9.0
tblib                             1.7.0
tenacity                          8.2.3
terminado                         0.17.1
text-unidecode                    1.3
textdistance                      4.2.1
threadpoolctl                     3.5.0
three-merge                       0.1.1
tifffile                          2023.4.12
tinycss2                          1.2.1
tldextract                        5.1.2
toml                              0.10.2
tomli                             2.0.1
tomlkit                           0.11.1
toolz                             0.12.0
torch                             2.7.1
torchvision                       0.22.1
tornado                           6.4.1
tqdm                              4.66.5
traitlets                         5.14.3
truststore                        0.8.0
Twisted                           23.10.0
typer                             0.9.0
typing_extensions                 4.11.0
tzdata                            2023.3
uc-micro-py                       1.0.1
ujson                             5.10.0
unicodedata2                      15.1.0
Unidecode                         1.3.8
urllib3                           2.2.3
w3lib                             2.1.2
watchdog                          4.0.1
wcwidth                           0.2.5
webencodings                      0.5.1
websocket-client                  1.8.0
Werkzeug                          3.0.3
whatthepatch                      1.0.2
wheel                             0.44.0
widgetsnbextension                3.6.6
wrapt                             1.14.1
wurlitzer                         3.0.2
xarray                            2023.6.0
xlwings                           0.32.1
xyzservices                       2022.9.0
yapf                              0.40.2
yarl                              1.11.0
zict                              3.0.0
zipp                              3.17.0
zope.interface                    5.4.0
zstandard                         0.23.0

Based on this I uninstalled PyQt5 by using
`pip uninstall qtpy PyQt5`

I checked if PyQt5 was successfully removed and got:
aext-assistant                    4.20.0
aext-assistant-server             4.20.0
aext-core                         4.20.0
aext-core-server                  4.20.0
aext_environments_server          4.20.0
aext-panels                       4.20.0
aext-panels-server                4.20.0
aext-project-filebrowser-server   4.20.0
aext-share-notebook               4.20.0
aext-share-notebook-server        4.20.0
aext-shared                       4.20.0
aext-toolbox                      4.20.0
aiobotocore                       2.12.3
aiohappyeyeballs                  2.4.0
aiohttp                           3.10.5
aioitertools                      0.7.1
aiosignal                         1.2.0
alabaster                         0.7.16
alembic                           1.13.3
altair                            5.0.1
anaconda-anon-usage               0.4.4
anaconda-auth                     0.8.6
anaconda-catalogs                 0.2.0
anaconda-cli-base                 0.5.2
anaconda-client                   1.13.0
anaconda-navigator                2.6.6
anaconda-project                  0.11.1
annotated-types                   0.6.0
anyio                             4.2.0
appdirs                           1.4.4
applaunchservices                 0.3.0
appnope                           0.1.3
appscript                         1.2.5
archspec                          0.2.3
argon2-cffi                       21.3.0
argon2-cffi-bindings              21.2.0
arrow                             1.2.3
astroid                           2.14.2
astropy                           6.1.3
astropy-iers-data                 0.2024.9.2.0.33.23
asttokens                         2.0.5
async-lru                         2.0.4
atomicwrites                      1.4.0
attrs                             23.1.0
Automat                           20.2.0
autopep8                          2.0.4
Babel                             2.11.0
bcrypt                            3.2.0
beautifulsoup4                    4.12.3
binaryornot                       0.4.4
black                             24.8.0
bleach                            4.1.0
blinker                           1.6.2
bokeh                             3.6.0
boltons                           23.0.0
botocore                          1.34.69
Bottleneck                        1.3.7
Brotli                            1.0.9
cachetools                        5.3.3
cellpose                          4.0.4
certifi                           2025.4.26
cffi                              1.17.1
chardet                           4.0.0
charset-normalizer                3.3.2
click                             8.1.7
cloudpickle                       3.0.0
colorama                          0.4.6
colorcet                          3.1.0
comm                              0.2.1
conda                             24.11.3
conda-build                       24.9.0
conda-content-trust               0.2.0
conda_index                       0.5.0
conda-libmamba-solver             24.9.0
conda-pack                        0.7.1
conda-package-handling            2.3.0
conda_package_streaming           0.10.0
conda-repo-cli                    1.0.114
conda-token                       0.6.0
constantly                        23.10.4
contourpy                         1.2.0
cookiecutter                      2.6.0
cryptography                      43.0.0
cssselect                         1.2.0
cycler                            0.11.0
cytoolz                           0.12.2
dask                              2024.8.2
dask-expr                         1.1.13
datashader                        0.16.3
debugpy                           1.6.7
decorator                         5.1.1
defusedxml                        0.7.1
diff-match-patch                  20200713
dill                              0.3.8
distributed                       2024.8.2
distro                            1.9.0
dmglib                            0.9.5
docstring-to-markdown             0.11
docutils                          0.18.1
et-xmlfile                        1.1.0
executing                         0.8.3
fastjsonschema                    2.16.2
fastremap                         1.16.1
filelock                          3.13.1
fill_voids                        2.1.0
flake8                            7.0.0
Flask                             3.0.3
fonttools                         4.51.0
frozendict                        2.4.2
frozenlist                        1.4.0
fsspec                            2024.6.1
gensim                            4.3.3
gitdb                             4.0.7
GitPython                         3.1.43
greenlet                          3.0.1
h11                               0.14.0
h5py                              3.11.0
HeapDict                          1.0.1
holoviews                         1.19.1
httpcore                          1.0.2
httpx                             0.27.0
hvplot                            0.11.0
hyperlink                         21.0.0
idna                              3.7
imagecodecs                       2023.1.23
imageio                           2.33.1
imagesize                         1.4.1
imbalanced-learn                  0.12.3
importlib-metadata                7.0.1
incremental                       22.10.0
inflection                        0.5.1
iniconfig                         1.1.1
intake                            2.0.7
intervaltree                      3.1.0
ipykernel                         6.28.0
ipython                           8.27.0
ipython-genutils                  0.2.0
ipywidgets                        7.8.1
isort                             5.13.2
itemadapter                       0.3.0
itemloaders                       1.1.0
itsdangerous                      2.2.0
jaraco.classes                    3.2.1
jedi                              0.19.1
jellyfish                         1.0.1
Jinja2                            3.1.4
jmespath                          1.0.1
joblib                            1.4.2
json5                             0.9.6
jsonpatch                         1.33
jsonpointer                       2.1
jsonschema                        4.23.0
jsonschema-specifications         2023.7.1
jupyter                           1.0.0
jupyter_client                    8.6.0
jupyter-console                   6.6.3
jupyter_core                      5.7.2
jupyter-events                    0.10.0
jupyter-lsp                       2.2.0
jupyter_server                    2.14.1
jupyter_server_terminals          0.4.4
jupyterlab                        4.2.5
jupyterlab-pygments               0.1.2
jupyterlab_server                 2.27.3
jupyterlab-widgets                1.0.0
keyring                           24.3.1
kiwisolver                        1.4.4
lazy_loader                       0.4
lazy-object-proxy                 1.10.0
lckr_jupyterlab_variableinspector 3.1.0
libarchive-c                      5.1
libmambapy                        1.5.8
linkify-it-py                     2.0.0
llvmlite                          0.43.0
lmdb                              1.4.1
locket                            1.0.0
lxml                              5.2.1
lz4                               4.3.2
Mako                              1.2.3
Markdown                          3.4.1
markdown-it-py                    2.2.0
MarkupSafe                        2.1.3
matplotlib                        3.9.2
matplotlib-inline                 0.1.6
mccabe                            0.7.0
mdit-py-plugins                   0.3.0
mdurl                             0.1.0
menuinst                          2.1.2
mistune                           2.0.4
more-itertools                    10.3.0
mpmath                            1.3.0
msgpack                           1.0.3
multidict                         6.0.4
multipledispatch                  0.6.0
mypy                              1.11.2
mypy-extensions                   1.0.0
natsort                           8.4.0
navigator-updater                 0.5.1
nb_conda_kernels                  2.5.2
nbclient                          0.8.0
nbconvert                         7.16.4
nbformat                          5.10.4
nest-asyncio                      1.6.0
networkx                          3.3
nltk                              3.9.1
notebook                          7.2.2
notebook_shim                     0.2.3
numba                             0.60.0
numexpr                           2.8.7
numpy                             1.26.4
numpydoc                          1.7.0
opencv-python-headless            4.11.0.86
openpyxl                          3.1.5
overrides                         7.4.0
packaging                         24.1
pandas                            2.2.2
pandocfilters                     1.5.0
panel                             1.5.2
param                             2.1.1
parsel                            1.8.1
parso                             0.8.3
partd                             1.4.1
pathspec                          0.10.3
patsy                             0.5.6
pexpect                           4.8.0
pickleshare                       0.7.5
pillow                            10.4.0
pip                               24.2
pkce                              1.0.3
pkginfo                           1.10.0
platformdirs                      3.10.0
plotly                            5.24.1
pluggy                            1.0.0
ply                               3.11
prometheus-client                 0.14.1
prompt-toolkit                    3.0.43
Protego                           0.1.16
protobuf                          4.25.3
psutil                            5.9.0
ptyprocess                        0.7.0
pure-eval                         0.2.2
py-cpuinfo                        9.0.0
pyarrow                           16.1.0
pyasn1                            0.4.8
pyasn1-modules                    0.2.8
pycodestyle                       2.11.1
pycosat                           0.6.6
pycparser                         2.21
pyct                              0.5.0
pycurl                            7.45.3
pydantic                          2.8.2
pydantic_core                     2.20.1
pydantic-settings                 2.6.1
pydeck                            0.8.0
PyDispatcher                      2.0.5
pydocstyle                        6.3.0
pyerfa                            2.0.1.4
pyflakes                          3.2.0
Pygments                          2.15.1
PyJWT                             2.8.0
pylint                            2.16.2
pylint-venv                       3.0.3
pyls-spyder                       0.4.0
pyobjc-core                       10.1
pyobjc-framework-Cocoa            10.1
pyobjc-framework-CoreServices     10.1
pyobjc-framework-FSEvents         10.1
pyodbc                            5.1.0
pyOpenSSL                         24.2.1
pyparsing                         3.1.2
PyQt5-sip                         12.13.0
PyQt6                             6.9.1
PyQt6-Qt6                         6.9.1
PyQt6_sip                         13.10.2
pyqtgraph                         0.13.7
PyQtWebEngine                     5.15.6
PySocks                           1.7.1
pytest                            7.4.4
python-dateutil                   2.9.0.post0
python-dotenv                     0.21.0
python-json-logger                2.0.7
python-lsp-black                  2.0.0
python-lsp-jsonrpc                1.1.2
python-lsp-server                 1.10.0
python-slugify                    5.0.2
pytoolconfig                      1.2.6
pytz                              2024.1
pyviz_comms                       3.0.2
PyWavelets                        1.7.0
PyYAML                            6.0.1
pyzmq                             25.1.2
QDarkStyle                        3.2.3
qstylizer                         0.2.2
QtAwesome                         1.3.1
qtconsole                         5.5.1
QtPy                              2.4.3
queuelib                          1.6.2
readchar                          4.0.5
referencing                       0.30.2
regex                             2024.9.11
requests                          2.32.3
requests-file                     1.5.1
requests-toolbelt                 1.0.0
rfc3339-validator                 0.1.4
rfc3986-validator                 0.1.1
rich                              13.7.1
roifile                           2025.5.10
rope                              1.12.0
rpds-py                           0.10.6
Rtree                             1.0.1
ruamel.yaml                       0.18.6
ruamel.yaml.clib                  0.2.8
ruamel-yaml-conda                 0.17.21
s3fs                              2024.6.1
scikit-image                      0.24.0
scikit-learn                      1.5.1
scipy                             1.13.1
Scrapy                            2.11.1
seaborn                           0.13.2
segment-anything                  1.0
semver                            3.0.2
Send2Trash                        1.8.2
sentry-sdk                        2.18.0
service-identity                  18.1.0
setuptools                        75.1.0
shellingham                       1.5.0
sip                               6.7.12
six                               1.16.0
smart-open                        5.2.1
smmap                             4.0.0
sniffio                           1.3.0
snowballstemmer                   2.2.0
sortedcontainers                  2.4.0
soupsieve                         2.5
Sphinx                            7.3.7
sphinxcontrib-applehelp           1.0.2
sphinxcontrib-devhelp             1.0.2
sphinxcontrib-htmlhelp            2.0.0
sphinxcontrib-jsmath              1.0.1
sphinxcontrib-qthelp              1.0.3
sphinxcontrib-serializinghtml     1.1.10
spyder                            5.5.1
spyder-kernels                    2.5.0
SQLAlchemy                        2.0.34
stack-data                        0.2.0
statsmodels                       0.14.2
streamlit                         1.37.1
superqt                           0.7.5
sympy                             1.14.0
tables                            3.10.1
tabulate                          0.9.0
tblib                             1.7.0
tenacity                          8.2.3
terminado                         0.17.1
text-unidecode                    1.3
textdistance                      4.2.1
threadpoolctl                     3.5.0
three-merge                       0.1.1
tifffile                          2023.4.12
tinycss2                          1.2.1
tldextract                        5.1.2
toml                              0.10.2
tomli                             2.0.1
tomlkit                           0.11.1
toolz                             0.12.0
torch                             2.7.1
torchvision                       0.22.1
tornado                           6.4.1
tqdm                              4.66.5
traitlets                         5.14.3
truststore                        0.8.0
Twisted                           23.10.0
typer                             0.9.0
typing_extensions                 4.11.0
tzdata                            2023.3
uc-micro-py                       1.0.1
ujson                             5.10.0
unicodedata2                      15.1.0
Unidecode                         1.3.8
urllib3                           2.2.3
w3lib                             2.1.2
watchdog                          4.0.1
wcwidth                           0.2.5
webencodings                      0.5.1
websocket-client                  1.8.0
Werkzeug                          3.0.3
whatthepatch                      1.0.2
wheel                             0.44.0
widgetsnbextension                3.6.6
wrapt                             1.14.1
wurlitzer                         3.0.2
xarray                            2023.6.0
xlwings                           0.32.1
xyzservices                       2022.9.0
yapf                              0.40.2
yarl                              1.11.0
zict                              3.0.0
zipp                              3.17.0
zope.interface                    5.4.0
zstandard                         0.23.0

Then I tried re-running cellpose but I got this new error: " qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""

What happened? How can I solve this?

Thanks in advance for the help!

**Comment by rockystones** [comment]
Just want to provide another data point and potential solution, this bug can also appear when there is a version mismatch with PyQt6. The issue is resolved after updating the PyQt6 PyQt6-Qt6 PyQt6-sip.

I updated the cellpose from v3 to v4.1.1 using` python -m pip install cellpose --upgrade` and then ran into the same bug: 
`AttributeError: 'QCheckBox' object has no attribute 'checkStateChanged'`

My pip list was: 
```
Package                  Version
------------------------ ---------
astroid                  2.4.1
Brotli                   1.0.9
cachetools               5.3.3
cellpose                 4.1.1
certifi                  2024.2.2
charset-normalizer       2.0.4
colorama                 0.4.3
fastremap                1.14.1
filelock                 3.13.1
fill_voids               2.1.2
fsspec                   2024.3.1
gmpy2                    2.1.2
google-api-core          2.18.0
google-auth              2.29.0
google-cloud-core        2.4.1
google-cloud-storage     2.16.0
google-crc32c            1.5.0
google-resumable-media   2.7.0
googleapis-common-protos 1.63.0
idna                     3.4
imagecodecs              2023.3.16
importlib_metadata       7.1.0
isort                    4.3.21
Jinja2                   3.1.3
lazy-object-proxy        1.4.3
llvmlite                 0.41.1
MarkupSafe               2.1.3
mkl-fft                  1.3.8
mkl-random               1.2.4
mkl-service              2.4.0
mpmath                   1.3.0
natsort                  8.4.0
networkx                 3.1
numba                    0.58.1
numpy                    1.24.3
opencv-python-headless   4.9.0.80
packaging                24.0
pillow                   10.2.0
pip                      23.3.1
proto-plus               1.23.0
protobuf                 4.25.3
pyasn1                   0.6.0
pyasn1_modules           0.4.0
Pygments                 2.17.2
pylint                   2.5.2
PyQt6                    6.6.1
PyQt6-Qt6                6.6.3
PyQt6-sip                13.6.0
pyqtgraph                0.13.3
PySocks                  1.7.1
PyYAML                   6.0.1
QtPy                     2.4.1
requests                 2.31.0
roifile                  2023.5.12
rsa                      4.9
scipy                    1.10.1
segment-anything         1.0
setuptools               68.2.2
six                      1.15.0
superqt                  0.6.3
sympy                    1.12
tifffile                 2023.7.10
toml                     0.10.1
torch                    2.2.2
torchaudio               2.2.2
torchvision              0.17.2
tqdm                     4.66.2
typing_extensions        4.11.0
urllib3                  2.1.0
wheel                    0.41.2
win-inet-pton            1.1.0
wrapt                    1.12.1
zipp                     3.18.1
```

Used Gemini to help me debug. Here are the Gemini analysis and solution that resolved this issue. 

The Cause
PyQt6 version incompatibility with checkStateChanged vs. deprecated stateChanged and Cellpose's likely code update. It's a strict version mismatch issue with your PyQt6 installation.
The Cellpose GUI recently updated its codebase to use the checkStateChanged signal for its checkboxes. According to the [Qt Documentation](https://doc.qt.io/qt-6/qcheckbox.html), this specific signal was officially introduced in Qt 6.7 (replacing the older stateChanged signal).

If you look closely at your pip list, you currently have PyQt6 version 6.6.1 installed. Because your version is older than 6.7, Python throws that AttributeError because the checkStateChanged attribute literally doesn't exist in your version of PyQt6 yet.

(Note: The GitHub issue you were looking at mentions conflicts between PyQt5 and PyQt6 as a common culprit, but your pip list is completely clean of PyQt5. Your only blocker is the outdated PyQt6 version!)

The Solution
To fix this, you just need to upgrade your PyQt6 packages to version 6.7 or newer. Upgrading to 6.9.0+ is highly recommended, as other Cellpose users have reported that it perfectly resolves this bug.

1. Open your Anaconda Prompt.

2. Ensure your Cellpose environment is active:

Bash
`conda activate cellpose`
3. Run the following command to upgrade your PyQt6 packages:

Bash
`pip install --upgrade PyQt6 PyQt6-Qt6 PyQt6-sip`

Once the newer version of PyQt6 is installed, try running `python -m cellpose` again. The GUI should launch without any errors!
